language: node_js
node_js:
  - "14"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test

before_deploy:
  - npm run build

deploy:
  provider: script
  script: npx vercel --prod --token $VERCEL_TOKEN
  skip_cleanup: true
  on:
    branch: main
